# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

steps:
- task: CacheBeta@0
  inputs:
    key: yarn | $(Agent.OS) | yarn.lock
    path: $(YARN_CACHE_FOLDER)
  displayName: Cache Yarn packages

- script: yarn --frozen-lockfile

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    node_8_x:
          node_version: 8.x
    node_10_x:
          node_version: 10.x
    node_12_x:
          node_version: 12.x

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
  displayName: 'Install Node.js'

- script: |
    yarn
    yarn run test
    yarn run build
  displayName: 'yarn install will install the dependencies \nYarn will run the unit tests in the project, \nand finally, yarn build will build the packages once the test results are Green.\nThen the project is ready to publish.'
